name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest
        
    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          mkdir -p ~/app
          mkdir -p ~/app-temp
          
          cd ~/app-temp
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
          
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          
          sudo tee /etc/systemd/system/hello-api.service << EOF
          [Unit]
          Description=Hello API Service
          After=network.target
          
          [Service]
          User=${{ secrets.VM_USERNAME }}
          WorkingDirectory=/home/${{ secrets.VM_USERNAME }}/app
          Environment="PATH=/home/${{ secrets.VM_USERNAME }}/app/venv/bin"
          ExecStart=/home/${{ secrets.VM_USERNAME }}/app/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 80
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          sudo systemctl stop hello-api || true
          
          rm -rf ~/app/*
          cp -r ~/app-temp/* ~/app/
          cp -r ~/app-temp/venv ~/app/
          
          sudo systemctl daemon-reload
          sudo systemctl start hello-api
          sudo systemctl enable hello-api
          
          rm -rf ~/app-temp
